version: "3.9"  # optional since v1.27.0
services:
  spring:
    build: demo/
    ports:
      - 8080:8080
  prometheus:
    build: prometheus/
    ports:
      - 9090:9090
    depends_on:
      - spring
  grafana:
    build: grafana/
    ports:
      - 3000:3000
    depends_on:
      - prometheus