scrape_configs:
- job_name:       'spring-actuator'
  scrape_interval: 10s
  metrics_path: '/actuator/prometheus'

  static_configs:
  - targets: ['spring-app:8080']
    labels:
      application: 'spring-app'